import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          min-h-screen 
          w-full 
          antialiased 
          flex 
          flex-col 
          overflow-x-hidden
          selection:bg-gray-200
          text-base
          md:text-[16px]
          lg:text-[18px]
          dark:bg-gray-900
          dark:text-white
        `}
      >
        <div className="flex-1 mx-auto w-full max-w-screen-2xl px-4 sm:px-6 md:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}